services:
  react:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: osonwa-frontend
    volumes:
      - ./node_modules:/app/node_modules
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - ./:/app:ro
    ports:
      - 3000:3000